### ISSUE TITLE
To-do list before/after Alpha release

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#84]
- [x] Add vanilla items to creative menu
- [x] Add Conquest textures to 1.15 blocks (bees etc)
- [ ] Add textures/models (stuff Monster, Artemisia, Whee, and DeChoppy have been working on)
- [ ] Add custom currency (Monster slight color change for other types)?
- [ ] Finish changelog
- [ ] Bugtest with Optifine

I'm sure I've missed some stuff so feel free to elaborate on some of the topics and add more if needed.

**Comment by HIPPOKLEIDES** [comment]
Changelog is really the only one necessary before a release. The rest are fine if they're left for after the release.
